CREATE DATABASE ESCOLA_TECNICA;
USE ESCOLA_TECNICA;

CREATE TABLE ALUNOS(
	ID INT AUTO_INCREMENT, 
	NOME VARCHAR(45), 
	EMAIL VARCHAR(45),
	DATA_NASCIMENTO DATE,
	PRIMARY KEY(ID) 
);

CREATE TABLE CURSOS(
	ID INT AUTO_INCREMENT,
	NOME_CURSO VARCHAR(45),
	CARGA_HORARIA INT,
	PRIMARY KEY(ID)
);
CREATE TABLE MATRICULAS (
	ID INT AUTO_INCREMENT,
	DATA_MATRICULA DATE,
    ALUNOS_ID INT,
    CURSOS_ID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (ALUNOS_ID) REFERENCES ALUNOS (ID),
    FOREIGN KEY (CURSOS_ID) REFERENCES CURSOS (ID)
);
	

INSERT INTO ALUNOS (NOME, EMAIL, DATA_NASCIMENTO) VALUES
('ANA', 'ANA.GMAIL.COM', '2000-01-28'),
('LUCAS', 'LUCAS.GMAIL.COM', '2001-08-06'),
('YGOR',' YGOR.GMAIL', '2000-02-04');

INSERT INTO CURSOS (NOME_CURSO, CARGA_HORARIA) VALUES
('MECANICA', 1200),
('ELETRONICA', 1300),
('ELETRICA', 1200),
('SISTEMAS', 1200),
('MODA', 1300),
('QUIMICA', 1200);

INSERT INTO MATRICULAS(DATA_MATRICULA, ALUNOS_ID,CURSOS_ID) VALUES
('2025-02-10',1,1),
('2025-02-10',2,2),
('2025-02-10',3,3);